### ISSUE TITLE
toggle specific package by hotkey

### ISSUE THREAD

**Issue by lope** [robenkleene/toggle-packages#5]
hi, thanks for this great package. I'd like to request a feature :)

It would be cool to be able to toggle packages by hotkey instead of having to take my hands off the keyboard to use the mouse, so for example if I could do this it would be great:

```
'atom-text-editor':
  'ctrl-q': 'toggle-quotes:toggle'
  'ctrl-r': 'toggle-packages:rulerz'
```

Toggle quotes already has an option to run by hotkey.
But rulerz needs to be enabled and disabled, which is where your package comes in!

https://atom.io/packages/toggle-quotes
https://atom.io/packages/rulerz

**Comment by robenkleene** [comment]
Hi lope,

That's already supported, you almost had the syntax right but the command name is "Toggle Rulerz" therefore your line should look like this:
```
'ctrl-r': 'toggle-packages:toggle-rulerz'
```

I didn't test with that specific package, but here's an example I tested myself that works:

```
'atom-text-editor':
  'alt-x': 'toggle-packages:toggle-emmet'
```

Cheers!
-Roben

**Comment by lope** [comment]
Thanks very much for your reply, I got it working :)
I've sent a pull request so other people can easily see how to use your toggle-packages via a hotkey.
